Problem: powerful-integers
Submission ID: 1695586889
Submission Time: 2025-07-12 12:07:10
============================================================

State: SUCCESS
Status: Runtime Error
Language: Python

Runtime: N/A ms
Memory: 12.37 MB

Test Cases: 103/104 passed

Last Test Case:
Input: 2
3
0
Expected: []

============================================================
RAW SUBMISSION DATA
============================================================
{
  "status_code": 15,
  "lang": "python",
  "run_success": false,
  "runtime_error": "Line 16: ValueError: math domain error",
  "full_runtime_error": "ValueError: math domain error\n    log_x = int(math.floor(math.log(bound) / math.log(x)))+1 if x != 1 else 1\nLine 16 in powerfulIntegers (Solution.py)\n    ret = Solution().powerfulIntegers(param_1, param_2, param_3)\nLine 63 in _driver (Solution.py)\n    _driver()\nLine 77 in <module> (Solution.py)",
  "status_runtime": "N/A",
  "memory": 12372000,
  "question_id": "1010",
  "elapsed_time": 43,
  "compare_result": "11111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111110",
  "code_output": "",
  "std_output": "",
  "last_testcase": "2\n3\n0",
  "expected_output": "[]",
  "task_finish_time": 1752347229106,
  "task_name": "judger.judgetask.Judge",
  "finished": true,
  "total_correct": 103,
  "total_testcases": 104,
  "runtime_percentile": null,
  "status_memory": "N/A",
  "memory_percentile": null,
  "pretty_lang": "Python",
  "submission_id": "1695586889",
  "status_msg": "Runtime Error",
  "state": "SUCCESS"
}