Problem: recover-a-tree-from-preorder-traversal
Submission ID: 1695596209
Submission Time: 2025-07-12 12:18:41
============================================================

State: SUCCESS
Status: Runtime Error
Language: Python

Runtime: N/A ms
Memory: 12.51 MB

Test Cases: 0/105 passed

Last Test Case:
Input: "1-2--3--4-5--6--7"
Expected: [1,2,5,3,4,6,7]

============================================================
RAW SUBMISSION DATA
============================================================
{
  "status_code": 15,
  "lang": "python",
  "run_success": false,
  "runtime_error": "Line 98: TypeError: <__main__.TreeNode object at 0x7f18c48d7f10> is not valid value for the expected return type TreeNode",
  "full_runtime_error": "TypeError: <__main__.TreeNode object at 0x7f18c48d7f10> is not valid value for the expected return type TreeNode\n    raise TypeError(str(ret) + \" is not valid value for the expected return type TreeNode\");\nLine 98 in _driver (Solution.py)\n    _driver()\nLine 106 in <module> (Solution.py)",
  "status_runtime": "N/A",
  "memory": 12508000,
  "question_id": "1093",
  "elapsed_time": 33,
  "compare_result": "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "code_output": "",
  "std_output": "",
  "last_testcase": "\"1-2--3--4-5--6--7\"",
  "expected_output": "[1,2,5,3,4,6,7]",
  "task_finish_time": 1752347917707,
  "task_name": "judger.judgetask.Judge",
  "finished": true,
  "total_correct": 0,
  "total_testcases": 105,
  "runtime_percentile": null,
  "status_memory": "N/A",
  "memory_percentile": null,
  "pretty_lang": "Python",
  "submission_id": "1695596209",
  "status_msg": "Runtime Error",
  "state": "SUCCESS"
}