Problem: verifying-an-alien-dictionary
Submission ID: 1695739139
Submission Time: 2025-07-12 17:05:15
============================================================

State: SUCCESS
Status: Accepted
Language: Python

Runtime: 0 ms
Memory: 12.51 MB

Test Cases: 125/125 passed

Runtime Percentile: 100%
Memory Percentile: 16.376200000000004%

============================================================
RAW SUBMISSION DATA
============================================================
{
  "status_code": 10,
  "lang": "python",
  "run_success": true,
  "status_runtime": "0 ms",
  "memory": 12508000,
  "display_runtime": "0",
  "question_id": "990",
  "elapsed_time": 37,
  "compare_result": "11111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111",
  "code_output": "",
  "std_output": "",
  "last_testcase": "",
  "expected_output": "",
  "task_finish_time": 1752365115450,
  "task_name": "judger.judgetask.Judge",
  "finished": true,
  "total_correct": 125,
  "total_testcases": 125,
  "runtime_percentile": 100,
  "status_memory": "12.5 MB",
  "memory_percentile": 16.376200000000004,
  "pretty_lang": "Python",
  "submission_id": "1695739139",
  "status_msg": "Accepted",
  "state": "SUCCESS"
}