Problem: find-the-pivot-integer
Submission ID: 1695712307
Submission Time: 2025-07-12 15:48:46
============================================================

State: SUCCESS
Status: Accepted
Language: Python

Runtime: 0 ms
Memory: 12.49 MB

Test Cases: 428/428 passed

Runtime Percentile: 100%
Memory Percentile: 66.5199%

============================================================
RAW SUBMISSION DATA
============================================================
{
  "status_code": 10,
  "lang": "python",
  "run_success": true,
  "status_runtime": "0 ms",
  "memory": 12488000,
  "display_runtime": "0",
  "question_id": "2571",
  "elapsed_time": 41,
  "compare_result": "11111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111",
  "code_output": "",
  "std_output": "",
  "last_testcase": "",
  "expected_output": "",
  "task_finish_time": 1752360525183,
  "task_name": "judger.judgetask.Judge",
  "finished": true,
  "total_correct": 428,
  "total_testcases": 428,
  "runtime_percentile": 100,
  "status_memory": "12.5 MB",
  "memory_percentile": 66.5199,
  "pretty_lang": "Python",
  "submission_id": "1695712307",
  "status_msg": "Accepted",
  "state": "SUCCESS"
}